name: test_google_direction_api
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  http: ^1.5.0

  riverpod_annotation: ^2.3.0
  flutter_dotenv: ^5.2.1

  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  flutter_cache_manager: ^3.4.1

  hooks_riverpod: ^2.5.1

  # Freezed
  freezed_annotation: ^2.4.1

  # UI/スクロール制御
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8

  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.8

  font_awesome_flutter: ^10.7.0

  flutter_localizations:
    sdk: flutter

  fl_chart: ^0.69.0
  dotted_line: ^3.2.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.7
  riverpod_generator: ^2.3.2

  freezed: ^2.4.6
  json_serializable: ^6.7.1

  # Lint
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:

  uses-material-design: true

  assets:
    - .env
